# ECT_HW3_Part2
### 1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('customer_churn.csv')
df

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,54023,1,1.0,Computer,1,31.0,Debit Card,Male,4.0,5,Mobile Phone,1,Single,3,1,25.0,2.0,2.0,1.0,149
1,50266,0,16.0,Mobile Phone,1,18.0,Debit Card,Male,2.0,4,Grocery,4,Married,2,0,11.0,0.0,NaN,9.0,243
2,54985,0,16.0,Mobile Phone,1,36.0,Credit Card,Male,3.0,6,Laptop & Accessory,1,Single,6,0,20.0,2.0,2.0,1.0,168
3,52029,1,0.0,Phone,3,NaN,E wallet,Male,2.0,4,Mobile,4,Married,2,1,18.0,0.0,1.0,0.0,124
4,50084,0,13.0,Computer,1,15.0,Debit Card,Male,3.0,4,Laptop & Accessory,2,Divorced,10,0,14.0,1.0,1.0,2.0,149
5,52379,1,0.0,Computer,1,7.0,Debit Card,Female,3.0,1,Fashion,4,Single,2,0,11.0,1.0,4.0,7.0,174
6,54025,0,1.0,Computer,1,22.0,Debit Card,Female,4.0,5,Mobile Phone,5,Married,2,0,20.0,8.0,8.0,4.0,173
7,50545,1,2.0,Phone,1,NaN,CC,Male,3.0,3,Mobile,5,Divorced,8,1,21.0,1.0,2.0,2.0,124
8,51280,0,15.0,Computer,1,29.0,Debit Card,Male,2.0,4,Laptop & Accessory,3,Single,2,0,12.0,2.0,3.0,7.0,143
9,55246,1,1.0,Computer,1,10.0,Debit Card,Female,3.0,4,Mobile Phone,3,Single,3,0,13.0,3.0,8.0,8.0,166
10,53159,0,26.0,Mobile Phone,1,13.0,COD,Male,4.0,4,Laptop & Accessory,5,Married,5,1,13.0,3.0,7.0,10.0,181
11,51073,0,0.0,Phone,3,15.0,Debit Card,Male,NaN,3,Mobile,5,Single,2,0,11.0,0.0,1.0,2.0,127
12,53988,1,1.0,Phone,2,27.0,Credit Card,Female,4.0,4,Mobile Phone,4,Married,2,1,12.0,1.0,2.0,5.0,146
13,53450,0,19.0,Phone,2,31.0,Credit Card,Male,3.0,4,Mobile Phone,4,Single,3,0,17.0,1.0,2.0,5.0,147
14,54769,1,19.0,Mobile Phone,3,9.0,Credit Card,Male,3.0,4,Laptop & Accessory,1,Single,6,0,17.0,2.0,8.0,4.0,177
15,50329,1,0.0,Computer,2,23.0,Debit Card,Female,NaN,3,Mobile,3,Married,1,1,11.0,0.0,1.0,0.0,127
16,50311,1,0.0,Mobile Phone,1,21.0,Credit Card,Male,2.0,3,Fashion,3,Divorced,8,1,12.0,0.0,NaN,7.0,236
17,51881,0,14.0,Mobile Phone,2,16.0,UPI,Male,3.0,4,Others,1,Married,4,0,15.0,NaN,12.0,6.0,291
18,52789,0,15.0,Mobile Phone,1,8.0,Debit Card,Male,2.0,3,Others,3,Married,6,0,11.0,NaN,4.0,14.0,289
19,52027,0,11.0,Mobile Phone,1,6.0,Cash on Delivery,Female,3.0,3,Fashion,5,Married,2,0,13.0,4.0,NaN,11.0,236
20,52475,0,15.0,Mobile Phone,1,15.0,UPI,Male,3.0,4,Others,1,Single,9,0,NaN,1.0,1.0,1.0,296
21,54153,0,13.0,Mobile Phone,3,31.0,E wallet,Female,3.0,5,Grocery,1,Married,2,0,12.0,2.0,NaN,7.0,245
22,54104,0,1.0,Mobile Phone,1,9.0,UPI,Male,3.0,4,Mobile Phone,3,Married,8,1,20.0,1.0,2.0,3.0,165
23,51128,0,7.0,Phone,1,8.0,CC,Male,NaN,1,Mobile,1,Married,1,1,14.0,0.0,1.0,2.0,129
24,55357,0,15.0,Mobile Phone,3,30.0,Debit Card,Male,4.0,4,Fashion,3,Single,5,1,17.0,1.0,2.0,3.0,196
25,51146,0,7.0,Mobile Phone,3,9.0,Debit Card,Female,2.0,5,Laptop & Accessory,1,Single,6,0,12.0,1.0,2.0,2.0,160
26,53835,0,5.0,Computer,3,9.0,UPI,Male,3.0,4,Laptop & Accessory,5,Single,9,0,14.0,1.0,2.0,4.0,178
27,52451,0,6.0,Mobile Phone,3,14.0,Debit Card,Male,2.0,3,Laptop & Accessory,5,Married,3,0,13.0,2.0,2.0,2.0,164
28,52391,0,13.0,Phone,1,NaN,CC,Male,3.0,3,Mobile,3,Married,3,0,14.0,1.0,1.0,2.0,123
29,54303,0,12.0,Mobile Phone,1,10.0,COD,Female,3.0,4,Laptop & Accessory,3,Single,5,1,21.0,3.0,3.0,3.0,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,50946,0,1.0,Computer,3,13.0,Debit Card,Male,2.0,3,Laptop & Accessory,5,Single,1,0,14.0,1.0,1.0,3.0,149
3054,55028,0,24.0,Computer,1,9.0,Credit Card,Female,2.0,4,Grocery,5,Married,4,0,NaN,1.0,3.0,3.0,304
3055,50357,0,7.0,Phone,1,6.0,Debit Card,Male,2.0,4,Mobile Phone,2,Divorced,2,1,13.0,0.0,1.0,3.0,136
3056,52580,0,20.0,Computer,3,8.0,E wallet,Male,2.0,3,Laptop & Accessory,4,Married,8,0,11.0,0.0,1.0,0.0,150
3057,53838,0,23.0,Mobile Phone,1,32.0,Debit Card,Female,3.0,4,Mobile Phone,5,Married,3,0,15.0,1.0,2.0,5.0,157
3058,52724,0,15.0,Mobile Phone,3,18.0,E wallet,Male,3.0,3,Laptop & Accessory,1,Married,4,1,12.0,1.0,1.0,0.0,151
3059,54380,0,28.0,Mobile Phone,3,10.0,E wallet,Female,3.0,4,Laptop & Accessory,5,Married,4,0,15.0,2.0,2.0,6.0,184
3060,51922,0,0.0,Computer,3,14.0,E wallet,Male,2.0,3,Laptop & Accessory,1,Married,1,0,19.0,1.0,1.0,1.0,143
3061,50586,0,6.0,Computer,3,23.0,Debit Card,Male,2.0,3,Grocery,3,Single,2,0,11.0,NaN,6.0,0.0,274
3062,54514,0,11.0,Mobile Phone,1,13.0,Credit Card,Male,3.0,2,Laptop & Accessory,5,Married,6,1,14.0,7.0,7.0,8.0,185
3063,52395,0,3.0,Mobile Phone,3,22.0,Debit Card,Male,3.0,3,Laptop & Accessory,3,Married,9,0,15.0,1.0,2.0,2.0,153
3064,54990,1,1.0,Mobile Phone,3,16.0,E wallet,Female,4.0,4,Laptop & Accessory,5,Single,5,1,18.0,1.0,2.0,4.0,207
3065,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120
3066,53348,0,3.0,Mobile Phone,1,14.0,Credit Card,Female,4.0,5,Mobile Phone,2,Married,8,0,15.0,2.0,2.0,4.0,150
3067,53475,0,12.0,Mobile Phone,1,24.0,Debit Card,Female,4.0,5,Fashion,3,Divorced,2,0,19.0,1.0,2.0,NaN,213
3068,53636,0,24.0,Mobile Phone,1,35.0,Debit Card,Female,3.0,4,Grocery,5,Divorced,6,1,NaN,1.0,2.0,3.0,294
3069,50410,0,26.0,Mobile Phone,1,13.0,Debit Card,Male,2.0,2,Grocery,3,Divorced,4,0,19.0,0.0,NaN,3.0,248
3070,52790,1,19.0,Phone,1,NaN,COD,Male,3.0,3,Mobile,3,Married,9,0,11.0,6.0,9.0,8.0,123
3071,53666,1,19.0,Mobile Phone,3,20.0,E wallet,Male,3.0,2,Grocery,3,Single,8,1,18.0,NaN,4.0,9.0,262
3072,55159,0,1.0,Mobile Phone,1,9.0,Credit Card,Male,3.0,5,Mobile Phone,1,Single,2,0,13.0,2.0,2.0,2.0,164
3073,52009,1,0.0,Phone,1,24.0,UPI,Female,NaN,3,Mobile,1,Single,2,0,19.0,1.0,1.0,0.0,127
3074,51520,0,18.0,Mobile Phone,3,10.0,Debit Card,Female,1.0,3,Laptop & Accessory,5,Married,5,1,11.0,0.0,1.0,3.0,150
3075,51261,0,7.0,Mobile Phone,3,19.0,Credit Card,Male,2.0,3,Fashion,3,Married,2,0,18.0,1.0,1.0,1.0,186
3076,54400,1,1.0,Mobile Phone,1,7.0,Debit Card,Male,4.0,5,Mobile Phone,3,Single,2,1,15.0,1.0,2.0,3.0,162
3077,53640,0,13.0,Mobile Phone,1,25.0,Debit Card,Male,3.0,4,Laptop & Accessory,3,Single,2,0,12.0,1.0,2.0,8.0,170
3078,51224,0,13.0,Mobile Phone,1,6.0,Debit Card,Male,3.0,3,Grocery,5,Married,3,0,11.0,NaN,11.0,16.0,268
3079,51396,1,11.0,Mobile Phone,1,6.0,Debit Card,Male,3.0,4,Fashion,3,Single,10,1,13.0,0.0,1.0,0.0,154
3080,52017,0,NaN,Mobile Phone,1,16.0,Debit Card,Male,2.0,3,Mobile,4,Married,2,0,14.0,1.0,1.0,0.0,120
3081,50355,1,0.0,Computer,1,13.0,Debit Card,Female,NaN,3,Mobile,3,Divorced,2,1,16.0,0.0,1.0,2.0,129
3082,53803,1,2.0,Mobile Phone,1,9.0,Credit Card,Male,3.0,4,Laptop & Accessory,4,Married,6,0,12.0,1.0,2.0,5.0,174

### 2

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3083 entries, 0 to 3082
Data columns (total 20 columns):
CustomerID                     3083 non-null int64
Churn                          3083 non-null int64
Tenure                         2930 non-null float64
PreferredLoginDevice           3083 non-null object
CityTier                       3083 non-null int64
WarehouseToHome                2929 non-null float64
PreferredPaymentMode           3083 non-null object
Gender                         3083 non-null object
HourSpendOnApp                 2933 non-null float64
NumberOfDeviceRegistered       3083 non-null int64
PreferedOrderCat               3083 non-null object
SatisfactionScore              3083 non-null int64
MaritalStatus                  3083 non-null object
NumberOfAddress                3083 non-null int64
Complain                       3083 non-null int64
OrderAmountHikeFromlastYear    2952 non-null float64
CouponUsed                     2957 non-null float64
OrderCount                     2955 non-null float64
DaySinceLastOrder              2917 non-null float64
CashbackAmount                 3083 non-null int64
dtypes: float64(7), int64(8), object(5)
memory usage: 481.8+ KB

由上可知：<br>
資料筆數：3083<br>
屬性數量 : 20<br>
各類別資料筆數寫在第二列（3083,3083,2930,3083,...,2917,3083)

In [3]:
print("各欄位空值數量：")
df.isnull().sum()

各欄位空值數量：

CustomerID                       0
Churn                            0
Tenure                         153
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                154
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 150
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    131
CouponUsed                     126
OrderCount                     128
DaySinceLastOrder              166
CashbackAmount                   0
dtype: int64

### 3

In [4]:
df[df.duplicated()]

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
1220,50180,0,12.0,Mobile Phone,1,6.0,Credit Card,Male,2.0,2,Fashion,2,Married,1,0,17.0,3.0,3.0,7.0,196
2100,50135,1,0.0,Computer,1,35.0,CC,Male,3.0,4,Mobile,4,Single,1,0,11.0,1.0,1.0,4.0,135
2769,50135,1,0.0,Computer,1,35.0,CC,Male,3.0,4,Mobile,4,Single,1,0,11.0,1.0,1.0,4.0,135
2846,50081,1,0.0,Mobile Phone,3,33.0,E wallet,Female,2.0,3,Fashion,2,Divorced,2,0,22.0,1.0,1.0,9.0,176
2935,50180,0,12.0,Mobile Phone,1,6.0,Credit Card,Male,2.0,2,Fashion,2,Married,1,0,17.0,3.0,3.0,7.0,196

In [5]:
column_names = ['CustomerID', 'Churn', 'Tenure', 'PreferredLoginDevice', 'CityTier', 'WarehouseToHome', 'PreferredPaymentMode', 'Gender', 'HourSpendOnApp', 'NumberOfDeviceRegistered']
 
df.drop_duplicates(subset=column_names, keep='first', inplace=True)

In [6]:
df.info()
print('\n刪除重複資料後筆數：',len(df))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3078 entries, 0 to 3082
Data columns (total 20 columns):
CustomerID                     3078 non-null int64
Churn                          3078 non-null int64
Tenure                         2925 non-null float64
PreferredLoginDevice           3078 non-null object
CityTier                       3078 non-null int64
WarehouseToHome                2924 non-null float64
PreferredPaymentMode           3078 non-null object
Gender                         3078 non-null object
HourSpendOnApp                 2928 non-null float64
NumberOfDeviceRegistered       3078 non-null int64
PreferedOrderCat               3078 non-null object
SatisfactionScore              3078 non-null int64
MaritalStatus                  3078 non-null object
NumberOfAddress                3078 non-null int64
Complain                       3078 non-null int64
OrderAmountHikeFromlastYear    2947 non-null float64
CouponUsed                     2952 non-null float64
OrderCount                     2950 non-null float64
DaySinceLastOrder              2912 non-null float64
CashbackAmount                 3078 non-null int64
dtypes: float64(7), int64(8), object(5)
memory usage: 505.0+ KB

刪除重複資料後筆數： 3078

### 4

In [7]:
df.isnull()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3054,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3055,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3056,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3057,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3058,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3059,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3060,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3061,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3062,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3063,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3064,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3065,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3066,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3067,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
3068,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3069,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3070,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3071,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3072,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3073,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
3074,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3075,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3076,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3077,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3078,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3079,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3080,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3081,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
3082,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.groupby(['PreferredLoginDevice']).size()

PreferredLoginDevice
Computer         926
Mobile Phone    1455
Phone            697
dtype: int64

In [9]:
df.groupby(['PreferredPaymentMode']).size()

PreferredPaymentMode
CC                   145
COD                  225
Cash on Delivery      77
Credit Card          787
Debit Card          1255
E wallet             367
UPI                  222
dtype: int64

In [10]:
df.groupby(['Gender']).size()

Gender
Female    1228
Male      1850
dtype: int64

In [11]:
df.groupby(['PreferedOrderCat']).size()

PreferedOrderCat
Fashion                446
Grocery                198
Laptop & Accessory    1066
Mobile                 461
Mobile Phone           772
Others                 135
dtype: int64

In [12]:
df.groupby(['MaritalStatus']).size()

MaritalStatus
Divorced     433
Married     1545
Single      1100
dtype: int64

In [13]:
#將字串轉換成數字分類

#PreferredLoginDevice部分
df.loc[df.PreferredLoginDevice == 'Computer', 'PreferredLoginDevice'] = 0
df.loc[df.PreferredLoginDevice == 'Mobile Phone', 'PreferredLoginDevice'] = 1
df.loc[df.PreferredLoginDevice == 'Phone', 'PreferredLoginDevice'] = 2

#PreferredPaymentMode部分
df.loc[df.PreferredPaymentMode == 'CC', 'PreferredPaymentMode'] = 0
df.loc[df.PreferredPaymentMode == 'COD', 'PreferredPaymentMode'] = 1
df.loc[df.PreferredPaymentMode == 'Cash on Delivery', 'PreferredPaymentMode'] = 2
df.loc[df.PreferredPaymentMode == 'Credit Card', 'PreferredPaymentMode'] = 3
df.loc[df.PreferredPaymentMode == 'Debit Card', 'PreferredPaymentMode'] = 4
df.loc[df.PreferredPaymentMode == 'E wallet', 'PreferredPaymentMode'] = 5
df.loc[df.PreferredPaymentMode == 'UPI', 'PreferredPaymentMode'] = 6

#Gender部分
df.loc[df.Gender == 'Male', 'Gender'] = 0
df.loc[df.Gender == 'Female', 'Gender'] = 1

#PreferedOrderCat部分
df.loc[df.PreferedOrderCat == 'Fashion', 'PreferedOrderCat'] = 0
df.loc[df.PreferedOrderCat == 'Grocery', 'PreferedOrderCat'] = 1
df.loc[df.PreferedOrderCat == 'Laptop & Accessory', 'PreferedOrderCat'] = 2
df.loc[df.PreferedOrderCat == 'Mobile', 'PreferedOrderCat'] = 3
df.loc[df.PreferedOrderCat == 'Mobile Phone', 'PreferedOrderCat'] = 4
df.loc[df.PreferedOrderCat == 'Others', 'PreferedOrderCat'] = 5

#MaritalStatus部分
df.loc[df.MaritalStatus == 'Divorced', 'MaritalStatus'] = 0
df.loc[df.MaritalStatus == 'Married', 'MaritalStatus'] = 1
df.loc[df.MaritalStatus == 'Single', 'MaritalStatus'] = 2

df

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,54023,1,1.0,0,1,31.0,4,0,4.0,5,4,1,2,3,1,25.0,2.0,2.0,1.0,149
1,50266,0,16.0,1,1,18.0,4,0,2.0,4,1,4,1,2,0,11.0,0.0,NaN,9.0,243
2,54985,0,16.0,1,1,36.0,3,0,3.0,6,2,1,2,6,0,20.0,2.0,2.0,1.0,168
3,52029,1,0.0,2,3,NaN,5,0,2.0,4,3,4,1,2,1,18.0,0.0,1.0,0.0,124
4,50084,0,13.0,0,1,15.0,4,0,3.0,4,2,2,0,10,0,14.0,1.0,1.0,2.0,149
5,52379,1,0.0,0,1,7.0,4,1,3.0,1,0,4,2,2,0,11.0,1.0,4.0,7.0,174
6,54025,0,1.0,0,1,22.0,4,1,4.0,5,4,5,1,2,0,20.0,8.0,8.0,4.0,173
7,50545,1,2.0,2,1,NaN,0,0,3.0,3,3,5,0,8,1,21.0,1.0,2.0,2.0,124
8,51280,0,15.0,0,1,29.0,4,0,2.0,4,2,3,2,2,0,12.0,2.0,3.0,7.0,143
9,55246,1,1.0,0,1,10.0,4,1,3.0,4,4,3,2,3,0,13.0,3.0,8.0,8.0,166
10,53159,0,26.0,1,1,13.0,1,0,4.0,4,2,5,1,5,1,13.0,3.0,7.0,10.0,181
11,51073,0,0.0,2,3,15.0,4,0,NaN,3,3,5,2,2,0,11.0,0.0,1.0,2.0,127
12,53988,1,1.0,2,2,27.0,3,1,4.0,4,4,4,1,2,1,12.0,1.0,2.0,5.0,146
13,53450,0,19.0,2,2,31.0,3,0,3.0,4,4,4,2,3,0,17.0,1.0,2.0,5.0,147
14,54769,1,19.0,1,3,9.0,3,0,3.0,4,2,1,2,6,0,17.0,2.0,8.0,4.0,177
15,50329,1,0.0,0,2,23.0,4,1,NaN,3,3,3,1,1,1,11.0,0.0,1.0,0.0,127
16,50311,1,0.0,1,1,21.0,3,0,2.0,3,0,3,0,8,1,12.0,0.0,NaN,7.0,236
17,51881,0,14.0,1,2,16.0,6,0,3.0,4,5,1,1,4,0,15.0,NaN,12.0,6.0,291
18,52789,0,15.0,1,1,8.0,4,0,2.0,3,5,3,1,6,0,11.0,NaN,4.0,14.0,289
19,52027,0,11.0,1,1,6.0,2,1,3.0,3,0,5,1,2,0,13.0,4.0,NaN,11.0,236
20,52475,0,15.0,1,1,15.0,6,0,3.0,4,5,1,2,9,0,NaN,1.0,1.0,1.0,296
21,54153,0,13.0,1,3,31.0,5,1,3.0,5,1,1,1,2,0,12.0,2.0,NaN,7.0,245
22,54104,0,1.0,1,1,9.0,6,0,3.0,4,4,3,1,8,1,20.0,1.0,2.0,3.0,165
23,51128,0,7.0,2,1,8.0,0,0,NaN,1,3,1,1,1,1,14.0,0.0,1.0,2.0,129
24,55357,0,15.0,1,3,30.0,4,0,4.0,4,0,3,2,5,1,17.0,1.0,2.0,3.0,196
25,51146,0,7.0,1,3,9.0,4,1,2.0,5,2,1,2,6,0,12.0,1.0,2.0,2.0,160
26,53835,0,5.0,0,3,9.0,6,0,3.0,4,2,5,2,9,0,14.0,1.0,2.0,4.0,178
27,52451,0,6.0,1,3,14.0,4,0,2.0,3,2,5,1,3,0,13.0,2.0,2.0,2.0,164
28,52391,0,13.0,2,1,NaN,0,0,3.0,3,3,3,1,3,0,14.0,1.0,1.0,2.0,123
29,54303,0,12.0,1,1,10.0,1,1,3.0,4,2,3,2,5,1,21.0,3.0,3.0,3.0,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,50946,0,1.0,0,3,13.0,4,0,2.0,3,2,5,2,1,0,14.0,1.0,1.0,3.0,149
3054,55028,0,24.0,0,1,9.0,3,1,2.0,4,1,5,1,4,0,NaN,1.0,3.0,3.0,304
3055,50357,0,7.0,2,1,6.0,4,0,2.0,4,4,2,0,2,1,13.0,0.0,1.0,3.0,136
3056,52580,0,20.0,0,3,8.0,5,0,2.0,3,2,4,1,8,0,11.0,0.0,1.0,0.0,150
3057,53838,0,23.0,1,1,32.0,4,1,3.0,4,4,5,1,3,0,15.0,1.0,2.0,5.0,157
3058,52724,0,15.0,1,3,18.0,5,0,3.0,3,2,1,1,4,1,12.0,1.0,1.0,0.0,151
3059,54380,0,28.0,1,3,10.0,5,1,3.0,4,2,5,1,4,0,15.0,2.0,2.0,6.0,184
3060,51922,0,0.0,0,3,14.0,5,0,2.0,3,2,1,1,1,0,19.0,1.0,1.0,1.0,143
3061,50586,0,6.0,0,3,23.0,4,0,2.0,3,1,3,2,2,0,11.0,NaN,6.0,0.0,274
3062,54514,0,11.0,1,1,13.0,3,0,3.0,2,2,5,1,6,1,14.0,7.0,7.0,8.0,185
3063,52395,0,3.0,1,3,22.0,4,0,3.0,3,2,3,1,9,0,15.0,1.0,2.0,2.0,153
3064,54990,1,1.0,1,3,16.0,5,1,4.0,4,2,5,2,5,1,18.0,1.0,2.0,4.0,207
3065,50003,1,NaN,2,1,30.0,4,0,2.0,4,3,3,2,6,1,14.0,0.0,1.0,3.0,120
3066,53348,0,3.0,1,1,14.0,3,1,4.0,5,4,2,1,8,0,15.0,2.0,2.0,4.0,150
3067,53475,0,12.0,1,1,24.0,4,1,4.0,5,0,3,0,2,0,19.0,1.0,2.0,NaN,213
3068,53636,0,24.0,1,1,35.0,4,1,3.0,4,1,5,0,6,1,NaN,1.0,2.0,3.0,294
3069,50410,0,26.0,1,1,13.0,4,0,2.0,2,1,3,0,4,0,19.0,0.0,NaN,3.0,248
3070,52790,1,19.0,2,1,NaN,1,0,3.0,3,3,3,1,9,0,11.0,6.0,9.0,8.0,123
3071,53666,1,19.0,1,3,20.0,5,0,3.0,2,1,3,2,8,1,18.0,NaN,4.0,9.0,262
3072,55159,0,1.0,1,1,9.0,3,0,3.0,5,4,1,2,2,0,13.0,2.0,2.0,2.0,164
3073,52009,1,0.0,2,1,24.0,6,1,NaN,3,3,1,2,2,0,19.0,1.0,1.0,0.0,127
3074,51520,0,18.0,1,3,10.0,4,1,1.0,3,2,5,1,5,1,11.0,0.0,1.0,3.0,150
3075,51261,0,7.0,1,3,19.0,3,0,2.0,3,0,3,1,2,0,18.0,1.0,1.0,1.0,186
3076,54400,1,1.0,1,1,7.0,4,0,4.0,5,4,3,2,2,1,15.0,1.0,2.0,3.0,162
3077,53640,0,13.0,1,1,25.0,4,0,3.0,4,2,3,2,2,0,12.0,1.0,2.0,8.0,170
3078,51224,0,13.0,1,1,6.0,4,0,3.0,3,1,5,1,3,0,11.0,NaN,11.0,16.0,268
3079,51396,1,11.0,1,1,6.0,4,0,3.0,4,0,3,2,10,1,13.0,0.0,1.0,0.0,154
3080,52017,0,NaN,1,1,16.0,4,0,2.0,3,3,4,1,2,0,14.0,1.0,1.0,0.0,120
3081,50355,1,0.0,0,1,13.0,4,1,NaN,3,3,3,0,2,1,16.0,0.0,1.0,2.0,129
3082,53803,1,2.0,1,1,9.0,3,0,3.0,4,2,4,1,6,0,12.0,1.0,2.0,5.0,174

In [14]:
#空值部分直接以平均數帶入
df.fillna(df.mean(),inplace=True)
df

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,54023,1,1.000000,0,1,31.000000,4,0,4.000000,5,4,1,2,3,1,25.000000,2.000000,2.000000,1.000000,149
1,50266,0,16.000000,1,1,18.000000,4,0,2.000000,4,1,4,1,2,0,11.000000,0.000000,2.995593,9.000000,243
2,54985,0,16.000000,1,1,36.000000,3,0,3.000000,6,2,1,2,6,0,20.000000,2.000000,2.000000,1.000000,168
3,52029,1,0.000000,2,3,15.758208,5,0,2.000000,4,3,4,1,2,1,18.000000,0.000000,1.000000,0.000000,124
4,50084,0,13.000000,0,1,15.000000,4,0,3.000000,4,2,2,0,10,0,14.000000,1.000000,1.000000,2.000000,149
5,52379,1,0.000000,0,1,7.000000,4,1,3.000000,1,0,4,2,2,0,11.000000,1.000000,4.000000,7.000000,174
6,54025,0,1.000000,0,1,22.000000,4,1,4.000000,5,4,5,1,2,0,20.000000,8.000000,8.000000,4.000000,173
7,50545,1,2.000000,2,1,15.758208,0,0,3.000000,3,3,5,0,8,1,21.000000,1.000000,2.000000,2.000000,124
8,51280,0,15.000000,0,1,29.000000,4,0,2.000000,4,2,3,2,2,0,12.000000,2.000000,3.000000,7.000000,143
9,55246,1,1.000000,0,1,10.000000,4,1,3.000000,4,4,3,2,3,0,13.000000,3.000000,8.000000,8.000000,166
10,53159,0,26.000000,1,1,13.000000,1,0,4.000000,4,2,5,1,5,1,13.000000,3.000000,7.000000,10.000000,181
11,51073,0,0.000000,2,3,15.000000,4,0,2.946721,3,3,5,2,2,0,11.000000,0.000000,1.000000,2.000000,127
12,53988,1,1.000000,2,2,27.000000,3,1,4.000000,4,4,4,1,2,1,12.000000,1.000000,2.000000,5.000000,146
13,53450,0,19.000000,2,2,31.000000,3,0,3.000000,4,4,4,2,3,0,17.000000,1.000000,2.000000,5.000000,147
14,54769,1,19.000000,1,3,9.000000,3,0,3.000000,4,2,1,2,6,0,17.000000,2.000000,8.000000,4.000000,177
15,50329,1,0.000000,0,2,23.000000,4,1,2.946721,3,3,3,1,1,1,11.000000,0.000000,1.000000,0.000000,127
16,50311,1,0.000000,1,1,21.000000,3,0,2.000000,3,0,3,0,8,1,12.000000,0.000000,2.995593,7.000000,236
17,51881,0,14.000000,1,2,16.000000,6,0,3.000000,4,5,1,1,4,0,15.000000,1.753388,12.000000,6.000000,291
18,52789,0,15.000000,1,1,8.000000,4,0,2.000000,3,5,3,1,6,0,11.000000,1.753388,4.000000,14.000000,289
19,52027,0,11.000000,1,1,6.000000,2,1,3.000000,3,0,5,1,2,0,13.000000,4.000000,2.995593,11.000000,236
20,52475,0,15.000000,1,1,15.000000,6,0,3.000000,4,5,1,2,9,0,15.713946,1.000000,1.000000,1.000000,296
21,54153,0,13.000000,1,3,31.000000,5,1,3.000000,5,1,1,1,2,0,12.000000,2.000000,2.995593,7.000000,245
22,54104,0,1.000000,1,1,9.000000,6,0,3.000000,4,4,3,1,8,1,20.000000,1.000000,2.000000,3.000000,165
23,51128,0,7.000000,2,1,8.000000,0,0,2.946721,1,3,1,1,1,1,14.000000,0.000000,1.000000,2.000000,129
24,55357,0,15.000000,1,3,30.000000,4,0,4.000000,4,0,3,2,5,1,17.000000,1.000000,2.000000,3.000000,196
25,51146,0,7.000000,1,3,9.000000,4,1,2.000000,5,2,1,2,6,0,12.000000,1.000000,2.000000,2.000000,160
26,53835,0,5.000000,0,3,9.000000,6,0,3.000000,4,2,5,2,9,0,14.000000,1.000000,2.000000,4.000000,178
27,52451,0,6.000000,1,3,14.000000,4,0,2.000000,3,2,5,1,3,0,13.000000,2.000000,2.000000,2.000000,164
28,52391,0,13.000000,2,1,15.758208,0,0,3.000000,3,3,3,1,3,0,14.000000,1.000000,1.000000,2.000000,123
29,54303,0,12.000000,1,1,10.000000,1,1,3.000000,4,2,3,2,5,1,21.000000,3.000000,3.000000,3.000000,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,50946,0,1.000000,0,3,13.000000,4,0,2.000000,3,2,5,2,1,0,14.000000,1.000000,1.000000,3.000000,149
3054,55028,0,24.000000,0,1,9.000000,3,1,2.000000,4,1,5,1,4,0,15.713946,1.000000,3.000000,3.000000,304
3055,50357,0,7.000000,2,1,6.000000,4,0,2.000000,4,4,2,0,2,1,13.000000,0.000000,1.000000,3.000000,136
3056,52580,0,20.000000,0,3,8.000000,5,0,2.000000,3,2,4,1,8,0,11.000000,0.000000,1.000000,0.000000,150
3057,53838,0,23.000000,1,1,32.000000,4,1,3.000000,4,4,5,1,3,0,15.000000,1.000000,2.000000,5.000000,157
3058,52724,0,15.000000,1,3,18.000000,5,0,3.000000,3,2,1,1,4,1,12.000000,1.000000,1.000000,0.000000,151
3059,54380,0,28.000000,1,3,10.000000,5,1,3.000000,4,2,5,1,4,0,15.000000,2.000000,2.000000,6.000000,184
3060,51922,0,0.000000,0,3,14.000000,5,0,2.000000,3,2,1,1,1,0,19.000000,1.000000,1.000000,1.000000,143
3061,50586,0,6.000000,0,3,23.000000,4,0,2.000000,3,1,3,2,2,0,11.000000,1.753388,6.000000,0.000000,274
3062,54514,0,11.000000,1,1,13.000000,3,0,3.000000,2,2,5,1,6,1,14.000000,7.000000,7.000000,8.000000,185
3063,52395,0,3.000000,1,3,22.000000,4,0,3.000000,3,2,3,1,9,0,15.000000,1.000000,2.000000,2.000000,153
3064,54990,1,1.000000,1,3,16.000000,5,1,4.000000,4,2,5,2,5,1,18.000000,1.000000,2.000000,4.000000,207
3065,50003,1,9.115897,2,1,30.000000,4,0,2.000000,4,3,3,2,6,1,14.000000,0.000000,1.000000,3.000000,120
3066,53348,0,3.000000,1,1,14.000000,3,1,4.000000,5,4,2,1,8,0,15.000000,2.000000,2.000000,4.000000,150
3067,53475,0,12.000000,1,1,24.000000,4,1,4.000000,5,0,3,0,2,0,19.000000,1.000000,2.000000,4.346154,213
3068,53636,0,24.000000,1,1,35.000000,4,1,3.000000,4,1,5,0,6,1,15.713946,1.000000,2.000000,3.000000,294
3069,50410,0,26.000000,1,1,13.000000,4,0,2.000000,2,1,3,0,4,0,19.000000,0.000000,2.995593,3.000000,248
3070,52790,1,19.000000,2,1,15.758208,1,0,3.000000,3,3,3,1,9,0,11.000000,6.000000,9.000000,8.000000,123
3071,53666,1,19.000000,1,3,20.000000,5,0,3.000000,2,1,3,2,8,1,18.000000,1.753388,4.000000,9.000000,262
3072,55159,0,1.000000,1,1,9.000000,3,0,3.000000,5,4,1,2,2,0,13.000000,2.000000,2.000000,2.000000,164
3073,52009,1,0.000000,2,1,24.000000,6,1,2.946721,3,3,1,2,2,0,19.000000,1.000000,1.000000,0.000000,127
3074,51520,0,18.000000,1,3,10.000000,4,1,1.000000,3,2,5,1,5,1,11.000000,0.000000,1.000000,3.000000,150
3075,51261,0,7.000000,1,3,19.000000,3,0,2.000000,3,0,3,1,2,0,18.000000,1.000000,1.000000,1.000000,186
3076,54400,1,1.000000,1,1,7.000000,4,0,4.000000,5,4,3,2,2,1,15.000000,1.000000,2.000000,3.000000,162
3077,53640,0,13.000000,1,1,25.000000,4,0,3.000000,4,2,3,2,2,0,12.000000,1.000000,2.000000,8.000000,170
3078,51224,0,13.000000,1,1,6.000000,4,0,3.000000,3,1,5,1,3,0,11.000000,1.753388,11.000000,16.000000,268
3079,51396,1,11.000000,1,1,6.000000,4,0,3.000000,4,0,3,2,10,1,13.000000,0.000000,1.000000,0.000000,154
3080,52017,0,9.115897,1,1,16.000000,4,0,2.000000,3,3,4,1,2,0,14.000000,1.000000,1.000000,0.000000,120
3081,50355,1,0.000000,0,1,13.000000,4,1,2.946721,3,3,3,0,2,1,16.000000,0.000000,1.000000,2.000000,129
3082,53803,1,2.000000,1,1,9.000000,3,0,3.000000,4,2,4,1,6,0,12.000000,1.000000,2.000000,5.000000,174

### 5

In [15]:
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn import svm
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


X = df.drop(['Churn'], axis = 1)
y = df['Churn']#要預測的欄位

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.5, random_state = 12)

### 6,7
SVM部分

In [16]:
#kernel = linear
svmModel = svm.SVR(C=1,kernel='linear') 
svmModel.fit(X_train, y_train)

SVR(C=1, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
svmscore = svmModel.score(X_test, y_test)
print('coefficient of determination:', svmscore)

coefficient of determination: -715957.1961205789

In [18]:
ys_pred = svmModel.predict(X_test)
print('Predicted response:', ys_pred, sep='\n')

Predicted response:
[ -93.04866696  387.70029544 -302.37813473 ... -175.6101656   333.95785426
 -171.5196085 ]

In [19]:
#### kernel = rbf
rbfModel = svm.SVR(C=6,kernel='rbf',degree=3,gamma='auto') 
rbfModel.fit(X_train, y_train)

SVR(C=6, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [20]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
rbfscore = rbfModel.score(X_test, y_test)
print('coefficient of determination:', rbfscore)

coefficient of determination: -0.003969481298049526

In [21]:
ysr_pred = rbfModel.predict(X_test)
print('Predicted response:', ysr_pred, sep='\n')

Predicted response:
[0.34361039 0.34318486 0.34316736 ... 0.34319898 0.34319898 0.34319865]

In [33]:
svcModel = svm.LinearSVC(C=1, max_iter=10000) 
svcModel.fit(X_train, y_train)

/Users/brian/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=10000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [34]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
cscore = svcModel.score(X_test, y_test)
print('coefficient of determination:', cscore)

coefficient of determination: 0.6887589343729694

In [35]:
ysvc_pred = svcModel.predict(X_test)
print('Predicted response:', ysvc_pred, sep='\n')

Predicted response:
[0 0 0 ... 0 0 0]

In [25]:
crbfModel=svm.SVC(kernel='rbf', gamma=0.7, C=1)
crbfModel.fit(X_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.7, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
crscore = crbfModel.score(X_test, y_test)
print('coefficient of determination:', crscore)

coefficient of determination: 0.6887589343729694

In [36]:
Model=svm.SVC(kernel='linear',C=1)
Model.fit(X_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [37]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
score = Model.score(X_test, y_test)
print('coefficient of determination:', score)

coefficient of determination: 0.8050682261208577

最後選擇此SVM模型 accuracy最高

In [38]:
y_pred = Model.predict(X_test)
print('Predicted response:', y_pred, sep='\n')

Predicted response:
[0 0 1 ... 1 0 1]

Logistic Regression部分

In [27]:
from sklearn.linear_model import LogisticRegression

lmodel = LogisticRegression()
lmodel.fit(X_train, y_train)

/Users/brian/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
lscore = lmodel.score(X_test, y_test)
print('coefficient of determination:', lscore)

coefficient of determination: 0.7992202729044834

In [29]:
yl_pred = lmodel.predict(X_test)
print('Predicted response:', yl_pred, sep='\n')

Predicted response:
[0 0 0 ... 1 0 1]

Decision Tree部分

In [30]:
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier(criterion='gini')
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [31]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
dtscore = dtree.score(X_test, y_test)
print('coefficient of determination:', dtscore)

coefficient of determination: 0.8687459389213775

In [32]:
ydt_pred = dtree.predict(X_test)
print('Predicted response:', ydt_pred, sep='\n')

Predicted response:
[1 0 1 ... 1 0 1]

### 8

In [45]:
svcaccuracy = accuracy_score(y_test, y_pred)
lraccuracy = accuracy_score(y_test, yl_pred)
dtaccuracy = accuracy_score(y_test, ydt_pred)

print("SVM accuracy: ", svcaccuracy,"\nLogistic Regression accuracy: ", lraccuracy,"\nDecision Tree accuracy:", dtaccuracy)

SVM accuracy:  0.8050682261208577
Logistic Regression accuracy:  0.7992202729044834
Decision Tree accuracy: 0.8687459389213775

### 9

In [48]:
svccm = confusion_matrix(y_test, y_pred)
lrcm = confusion_matrix(y_test, yl_pred)
dtcm = confusion_matrix(y_test, ydt_pred)


print("SVM confusion matrix: \n", svccm,"\nLogistic Regression confusion matrix: \n", lrcm, "\nDecision Tree confusion matrix: \n", dtcm)

SVM confusion matrix:
 [[1009   51]
 [ 249  230]]
Logistic Regression confusion matrix:
 [[964  96]
 [213 266]]
Decision Tree confusion matrix:
 [[956 104]
 [ 98 381]]

[預測為真實際為真(TP) 預測為真實際為假(FN)]<br>
[預測為假實際為真(FP) 預測為假實際為假(TN)]

TP+TN為所有預測中正確的<br>
TP+TN/TP+FN+FP+TN 表示Accuracy表全部中預測正確的比例